Add north arrows and scale bars to map figures
echo-air-model/echo-air pull request #42
Opened 2024-05-20 17:13 UTC by rosypctals

2024-05-20 17:14 UTC, rosypctals commented
I've added the text from test.txt after running pip list >test.txt in the issue and updated the requirements.txt! I'll also update the documentation

2024-05-22 17:42 UTC, lkoolik commented
Hi Amy, 

This looks great! No notes on your current edits. 

I tested the code with different configurations of the run options and realized we need to make the same edit in the `visualize_pwm_conc` function in `environmental_justice_calcs.py`.  Can you please make that edit, too? Then I can take a look and we can merge!

2024-06-04 00:00 UTC, rosypctals commented
I've added the same code to the visualize_pwm_conc function! I understand that this function is called when the user inputs an output resolution larger than the ISRM grid- what would an example of that be?

2024-06-04 18:04 UTC, lkoolik commented
> I've added the same code to the visualize_pwm_conc function! I understand that this function is called when the user inputs an output resolution larger than the ISRM grid- what would an example of that be?

Try running a test where the control file has the following option:
- OUTPUT RESOLUTION: C

2024-06-06 19:10 UTC, lkoolik requested changes
I think I need to click this "Finish your review" in order for it to show you these comments? I'm not sure but I am clicking it anyway

2024-06-06 19:10 UTC, lkoolik commented on requirements.txt
> +matplotlib-scalebar==0.8.1
whoops! you already did this -- great job!

2024-06-11 18:51 UTC, rosypctals commented on scripts/tool_utils.py
> +        Parameters:
I've reformatted the two methods to follow this!

2024-06-11 18:55 UTC, rosypctals commented on supporting/concentration_layer.py
> +    def visualize_individual_emissions(self, pollutant_name=''):
Yes, I'm so sorry! I removed this method and fixed the error in run_echo_air.py- I'll make sure to keep the code more separate in the future!

2024-06-12 23:00 UTC, lkoolik approved these changes

2024-06-12 23:13 UTC, merged